// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6d0zhrPv65o7K-Vkyxy9-RVakwu7YCcE',
    appId: '1:698390863336:web:b4af6e7dfe595300ef185d',
    messagingSenderId: '698390863336',
    projectId: 'academy-b79ff',
    authDomain: 'academy-b79ff.firebaseapp.com',
    storageBucket: 'academy-b79ff.appspot.com',
    measurementId: 'G-Z5EG3Z9KPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6cLnxSUIpVHd916qYHPvzGYmF29OHEvE',
    appId: '1:698390863336:android:7b3dfbd517afcca9ef185d',
    messagingSenderId: '698390863336',
    projectId: 'academy-b79ff',
    storageBucket: 'academy-b79ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV9yCuzEKZYse913KQFJoPfaaYIxbDLeg',
    appId: '1:698390863336:ios:73a280b57de3883aef185d',
    messagingSenderId: '698390863336',
    projectId: 'academy-b79ff',
    storageBucket: 'academy-b79ff.appspot.com',
    iosClientId:
        '698390863336-6bhf1ebdnbe9g970d10aduhk52nvbsuo.apps.googleusercontent.com',
    iosBundleId: 'com.example.academy',
  );
}
